// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajtynkqrdwkpzhxhpwbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqdHlua3FyZHdrcHpoeGhwd2JyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MjAxODEsImV4cCI6MjA2NDM5NjE4MX0.Ma42Or1f4vb2C7-yxccJ_0ruWXMty7f6RJ_M0AJNcM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);