// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gasvtbbpcdyujnygbgtv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdhc3Z0YmJwY2R5dWpueWdiZ3R2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0ODE2MjgsImV4cCI6MjA2NDA1NzYyOH0.KSE-T3I2dh8MTDwj1lNe-zO9gppKppt0pyz_iKkTrPw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);